NATS:
  host: "nats.cloud.gcm"
  port: 4222
  subject_case: "main_caseupdate"
  subject_alert: "main_alertupdate"
ElasticSearch:
  host: "datahook.cloud.gcm"
  port: 9200
  user: "writer"
  passwd: "XxZqesYXuk8C"
  prefix_case:
  index_case: "module_placeholder_elasticsearch_thehive_case"
  prefix_alert: ""
  index_alert: "module_placeholder_elasticsearch_thehive_alert"
MongoDB:
  host: "172.10.11.2"
  port: 27017
  user: "module_placeholder_elasticsearch"
  passwd: "gDbv5cf7*F2"
  namedb: "placeholder_elasticsearch"
Rules_proc_msg:
  directory: "rules"
  file_case: "msgrule_case.yaml"
  file_alert: "msgrule_alert.yaml"
