#    LOGGING настройки логирования
#
# msgTypeName - тип сообщения, от этого зависит в какой лог-файл будет отправлятся
#  сообщение, а также с каким префиксом оно будет дублироватся в консоль
# writingFile - нужно ли записывать сообщение в файл или только выводить в консоль
# writingStdout - нужно ли выводить сообщение в консоль
# pathDirectory - директория для записи лог-файлов
# maxFileSize - максимальный размер файла, после которого будет создаваться новый
#  файл, а текущий будет архивироваться
#
#    ZABBIX настройки подключения к серверу Zabbix
#
# isTransmit - триггер включения/отключения передачи
# networkHost - хост в формате ip или domainname для подклчения к серверу
# networkPort - сетевой порт
# zabbixHost - приемник сообщений
# zabbixKey - ключ приемника
# timeInterval - временной интервал в минутах, нужен для подтверждения активности модуля
# handshake - сообщение которое будет отправлятся для подтверждения активности
#
LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "objects",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 100000,
    }
  - {
      msgTypeName: "alert_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "case_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
ZABBIX:
  isTransmit: true
  networkHost: "zabbix.cloud.gcm"
  networkPort: 10051
  zabbixHost: "sib-server"
  zabbixKey: "placeholder_elasticsearch"
  timeInterval: 10
  handshake: "I'm still alive"
