#    LOGGING настройки логирования
#
# msgTypeName - тип сообщения, от этого зависит в какой лог-файл будет отправлятся
#  сообщение, а также с каким префиксом оно будет дублироватся в консоль
# writingFile - нужно ли записывать сообщение в файл или только выводить в консоль
# writingStdout - нужно ли выводить сообщение в консоль
# pathDirectory - директория для записи лог-файлов
# maxFileSize - максимальный размер файла, после которого будет создаваться новый
#  файл, а текущий будет архивироваться
#
#    ZABBIX настройки подключения к серверу Zabbix
#
# isTransmit - триггер включения/отключения передачи
# networkHost - хост в формате ip или domainname для подклчения к серверу
# networkPort - сетевой порт
# zabbixHost - приемник сообщений
# zabbixKey - ключ приемника
# timeInterval - временной интервал в минутах, нужен для подтверждения активности модуля
# handshake - сообщение которое будет отправлятся для подтверждения активности
#
LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "objects",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 100000,
    }
  - {
      msgTypeName: "alert_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "case_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "test_object_update",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 1000000,
    }
  - {
      msgTypeName: "test_object_replaced",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 1000000,
    }
ZABBIX:
  networkHost: "192.168.9.45"
  networkPort: 10051
  zabbixHost: "test-uchet-db.cloud.gcm"
  eventTypes:
    # для отслеживания ошибок
    - eventType: "error"
      zabbixKey: "placeholder_elasticsearch.error"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: ""
    # для информационных сообщений о выполненной работе
    - eventType: "info"
      zabbixKey: "placeholder_elasticsearch.info"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: "I'm still alive"
    # для регулярного отстукивания что модуль еще работает
    - eventType: "handshake"
      zabbixKey: "placeholder_elasticsearch.handshake"
      isTransmit: true
      handshake:
        timeInterval: 1
        message: "0"
