#    LOGGING настройки логирования
#
# msgTypeName - тип сообщения, от этого зависит в какой лог-файл будет отправлятся
#  сообщение, а также с каким префиксом оно будет дублироватся в консоль
# writingFile - нужно ли записывать сообщение в файл или только выводить в консоль
# writingStdout - нужно ли выводить сообщение в консоль
# pathDirectory - директория для записи лог-файлов
# maxFileSize - максимальный размер файла, после которого будет создаваться новый
#  файл, а текущий будет архивироваться
#
#    ZABBIXJSONRPC настройки взаимодействия с API Zabbix. Используется для обогащения
# кейсов загружаемых в Elasticsearch следующими данными:
# - геокод;
# - тип объекта;
# - субъект Российской Федерации;
# - ИНН.
#
# networkHost - хост в формате ip или domainname для подклчения к API JSON-RPC
# login - имя пользователя для авторизации
# passwd - пароль для авторизации
# connectionTimeout - время, в течении которого будут осуществлятся попытки подключения (необязательный параметр)
#
#    NCIRCC настройки для взаимодействия с НКЦКИ. Используется для обогащения кейсов
# загружаемых в Elasticsearch полным наименованием организации, объекта атаки, на русском
# языке
#
# url - уникальный идентификатор ресурса
# token - аутентификационный идентификатор
#
#    ZABBIX настройки подключения к серверу Zabbix
#
# isTransmit - триггер включения/отключения передачи
# networkHost - хост в формате ip или domainname для подклчения к серверу
# networkPort - сетевой порт
# zabbixHost - приемник сообщений
# zabbixKey - ключ приемника
# timeInterval - временной интервал в минутах, нужен для подтверждения активности модуля
# handshake - сообщение которое будет отправлятся для подтверждения активности
#
LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "objects",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 100000,
    }
  - {
      msgTypeName: "alert_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "case_raw_fields",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 10000,
    }
  - {
      msgTypeName: "test_object_update",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 1000000,
    }
  - {
      msgTypeName: "test_object_replaced",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 1000000,
    }
NCIRCC:
  url: "https://10.0.227.10/api/v2/companies"
  token: "fdd2c5e743960ec9ea80d1ff8868cc6d8439b02f4d61075efd69a46eaa52ff0e"
ZABBIXJSONRPC:
  networkHost: "192.168.9.45"
  login: "Cherry"
  passwd: "v-2ymX!aVg3eS*hC"
  connectionTimeout: 5
ZABBIX:
  networkHost: "192.168.9.45"
  networkPort: 10051
  zabbixHost: "test-uchet-db.cloud.gcm"
  eventTypes:
    # для отслеживания ошибок
    - eventType: "error"
      zabbixKey: "placeholder_elasticsearch.error"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: ""
    # для информационных сообщений о выполненной работе
    - eventType: "info"
      zabbixKey: "placeholder_elasticsearch.info"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: "I'm still alive"
    # для регулярного отстукивания что модуль еще работает
    - eventType: "handshake"
      zabbixKey: "placeholder_elasticsearch.handshake"
      isTransmit: true
      handshake:
        timeInterval: 1
        message: "0"
