NATS:
  host: "nats.cloud.gcm"
  port: 4222
ElasticSearch:
  send: false
  host: "datahook.cloud.gcm"
  port: 9200
  prefix:
  index: "module_placeholder_elasticsearch_test"
  user: "writer"
  passwd: "XxZqesYXuk8C"
MongoDB:
  host: "192.168.9.208"
  port: 37017
  user: "module_placeholder_elasticsearch"
  passwd: "gDbv5cf7*F2"
  namedb: "placeholder_elasticsearch"
